### ISSUE TITLE
UncheckedIOException with com.github.appreciated:card:2.0.0.beta1

### ISSUE THREAD

**Issue by frankrues** [appreciated/card#6]
I would really like to use your card component but with 2.0.0.beta1 I get the following exception:

```
java.io.UncheckedIOException: Failed to create directory 'C:\Users\Johannes\IdeaProjects\card\target\frontend'
	at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:217) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:288) ~[vaadin-spring-12.0.3.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4680) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5143) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_202]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_202]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_202]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_202]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:456) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:105) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:86) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:416) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:180) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) [spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at com.ricoh.sdced.spring.demo.SpringDemoApplication.main(SpringDemoApplication.java:22) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.1.7.RELEASE.jar:2.1.7.RELEASE]
Caused by: java.io.IOException: Unable to create directory C:\Users\Johannes\IdeaProjects\card\target\frontend
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2472) ~[commons-io-2.5.jar:2.5]
	at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:214) ~[flow-server-2.0.8.jar:2.0.8]
	... 44 common frames omitted
```

**Comment by appreciated** [comment]
@frankrues please check if this issue is fixed by 2.0.0.beta2

**Comment by frankrues** [comment]
Similar issue but not on card project but paper-ripple

java.io.UncheckedIOException: Failed to create directory 'C:\Users\Johannes\IdeaProjects\paper-ripple\target\frontend'

**Comment by appreciated** [comment]
Thanks for checking 👍

**Comment by appreciated** [comment]
Can you please recheck with [2.0.0.beta3](https://vaadin.com/directory/component/card/2.0.0.beta3)

**Comment by frankrues** [comment]
With 2.0.0.beta3 I have issues in my MainLayout which is using your app-layout-addon version 3.0.0.beta5 

Unfortunately I'm a newby in Vaadin and don't how to handle this issue. 

Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'clickable-card' in any template file declared using @'HtmlImport' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:128) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103) ~[flow-server-2.0.8.jar:2.0.8]
	at com.github.appreciated.card.AbstractCard.<init>(AbstractCard.java:22) ~[card-2.0.0.beta3.jar:2.0.0.beta3]
	at com.github.appreciated.card.ClickableCard.<init>(ClickableCard.java:41) ~[card-2.0.0.beta3.jar:2.0.0.beta3]
	at com.github.appreciated.card.RippleClickableCard.<init>(RippleClickableCard.java:36) ~[card-2.0.0.beta3.jar:2.0.0.beta3]
	at com.github.appreciated.card.RippleClickableCard.<init>(RippleClickableCard.java:32) ~[card-2.0.0.beta3.jar:2.0.0.beta3]
	at com.github.appreciated.card.RippleClickableCard.<init>(RippleClickableCard.java:28) ~[card-2.0.0.beta3.jar:2.0.0.beta3]
	at com.github.appreciated.app.layout.notification.component.NotificationView.<init>(NotificationView.java:28) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.DefaultNotificationComponentFactory.getComponent(DefaultNotificationComponentFactory.java:12) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.DefaultNotificationComponentFactory.getComponent(DefaultNotificationComponentFactory.java:9) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.NotificationHolder.getComponent(NotificationHolder.java:83) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]

**Comment by appreciated** [comment]
You are seeing this because you are using the compatibility mode. This add-on only supports the new npm mode. [Please read here how to migrate to V14 without compatibility mode](https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html).
